# Generated by Django 4.2.5 on 2024-03-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="resume",
            field=models.FileField(
                blank=True, max_length=200, null=True, upload_to="resumes/"
            ),
        ),
    ]
