# Generated by Django 4.2.5 on 2024-03-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_userprofile_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="skills",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
