# Generated by Django 4.2.5 on 2024-03-26 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_userprofile_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractionSummary",
            fields=[],
            options={
                "verbose_name": "Interaction Summary",
                "verbose_name_plural": "Interaction Summary",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("account.interaction",),
        ),
    ]
