# Generated by Django 4.2.5 on 2023-11-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0003_alter_job_description_alter_job_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
