# Generated by Django 4.2.5 on 2023-11-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0005_alter_job_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="category",
            field=models.CharField(default="Entry-Level", max_length=50),
        ),
    ]
