# Generated by Django 4.2.5 on 2023-11-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0006_alter_job_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="expires_at",
            field=models.DateTimeField(null=True),
        ),
    ]
