# Generated by Django 4.2.5 on 2023-11-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0007_alter_job_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
