# Generated by Django 4.2.5 on 2023-11-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0008_alter_job_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
