# Generated by Django 4.2.5 on 2023-12-25 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0009_alter_job_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 12, 25, 5, 34, 41, 926135, tzinfo=datetime.timezone.utc
                ),
                max_length=300,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="skills",
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
