# Generated by Django 4.2.5 on 2023-12-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0010_job_experience_job_skills_alter_job_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="role",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
