# Generated by Django 4.2.5 on 2023-12-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0011_job_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="industry",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
