# Generated by Django 4.2.5 on 2024-03-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0013_alter_job_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="category",
            field=models.CharField(default="Entry-Level", max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="industry",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
