# Generated by Django 4.2.5 on 2024-03-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0014_alter_job_category_alter_job_industry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("Full-Time", "Full-Time"),
                    ("Part-Time", "Part-Time"),
                    ("Contract", "Contract"),
                    ("Freelance", "Freelance"),
                ],
                default="Full-Time",
                max_length=255,
            ),
        ),
    ]
