# Generated by Django 4.2.5 on 2024-03-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0015_alter_job_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="experience",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="job",
            name="skills",
            field=models.CharField(max_length=1000),
        ),
    ]
