# Generated by Django 4.2.5 on 2024-03-26 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation", "0017_alter_job_description_alter_job_skills_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSummary",
            fields=[],
            options={
                "verbose_name": "Job Summary",
                "verbose_name_plural": "Job Summary",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("recommendation.job",),
        ),
    ]
